In [1]:
import pandas as pd

In [2]:
import random

In [3]:
# 1. Definir la cantidad de filas deseadas (1 millón)
cantidad = 1000000

In [4]:
#2. Conjunto de base de datos reales/coherentes para la simulación en cancún
influencers_pool = ["@caribe_mexicano", "@rivera_maya_life", "@yucatan_explorer", "@tulum_diares", "@nomada_mx"]
tipos_post_pool = ["foto", "video", "reel", "carrusel"]
fechas_pool = ["2026-09-07", "2026-10-27", "2026-12-03", "2026-12-12", "2026-06-27"]

In [5]:
#3. Creación del dataframe de 1,000,000 de registros usando comprensión de Listas
df_instagram = pd.DataFrame({
    "influencer": [random.choice(influencers_pool) for _ in range(cantidad)],
    "likes": [random.randint(100, 50000) for _ in range(cantidad)],
    "comentarios": [random.randint(5, 2500) for _ in range(cantidad)],
    "fecha": [random.choice(fechas_pool) for _ in range(cantidad)],
    "tipo_post": [random.choice(tipos_post_pool) for _ in range(cantidad)]
})

In [6]:
#Definimos la cantidad (1 millón de registros)
cantidad = 1000000

In [7]:
df_instagram.shape

(1000000, 5)

In [8]:
df_instagram.dtypes

influencer     object
likes           int64
comentarios     int64
fecha          object
tipo_post      object
dtype: object

In [9]:
df_instagram.head()

          influencer  likes  comentarios       fecha tipo_post
0      @tulum_diares  30703          515  2026-12-03      foto
1   @caribe_mexicano  48861           18  2026-09-07      reel
2  @yucatan_explorer  46181         1531  2026-12-12  carrusel
3   @caribe_mexicano  37517          534  2026-12-03  carrusel
4  @yucatan_explorer  31713          149  2026-12-03     video

In [10]:
df_instagram.memory_usage(deep=True).sum() / (1024**2)

np.float64(183.91598224639893)

In [11]:
print("Promedio de likes:", df_instagram["likes"].mean())
print("Promedio de comentarios:", df_instagram["comentarios"].mean())

Promedio de likes: 25045.383204
Promedio de comentarios: 1252.690601

In [12]:
df_instagram.groupby("tipo_post")[["likes", "comentarios"]].mean()

                  likes  comentarios
tipo_post
carrusel   25046.116811  1251.206616
foto       25029.712262  1252.006333
reel       25082.110604  1254.313801
video      25023.648482  1253.234232

In [13]:
df_instagram.groupby("influencer")["likes"].sum().sort_values(ascending=False)

influencer
@yucatan_explorer    5015921859
@tulum_diares        5013775969
@nomada_mx           5008208679
@caribe_mexicano     5005558368
@rivera_maya_life    5001918329
Name: likes, dtype: int64